// Code generated by mockery v2.0.0. DO NOT EDIT.

package value

import "github.com/stretchr/testify/mock"

// mockValidator is an autogenerated mock type for the validator type
type mockValidator struct {
	mock.Mock
}

// ValidateID provides a mock function with given fields: _a0
func (_m *mockValidator) ValidateID(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateSlug provides a mock function with given fields: _a0
func (_m *mockValidator) ValidateSlug(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateTitle provides a mock function with given fields: _a0
func (_m *mockValidator) ValidateTitle(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
