// Code generated by mockery v2.0.0. DO NOT EDIT.

package value

import mock "github.com/stretchr/testify/mock"

// mockSanitiser is an autogenerated mock type for the sanitiser type
type mockSanitiser struct {
	mock.Mock
}

// SanitiseID provides a mock function with given fields: _a0
func (_m *mockSanitiser) SanitiseID(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SanitiseSlug provides a mock function with given fields: _a0, _a1
func (_m *mockSanitiser) SanitiseSlug(_a0 string, _a1 string) string {
	ret := _m.Called(_a0, _a1)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SanitiseTitle provides a mock function with given fields: _a0
func (_m *mockSanitiser) SanitiseTitle(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
