// Code generated by "stringer -type=NodeKind -linecomment -output=node_string.go"; DO NOT EDIT.

package value

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeArtefact-0]
	_ = x[NodeSnippet-1]
}

const _NodeKind_name = "artefactsnippet"

var _NodeKind_index = [...]uint8{0, 8, 15}

func (i NodeKind) String() string {
	if i < 0 || i >= NodeKind(len(_NodeKind_index)-1) {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[i]:_NodeKind_index[i+1]]
}
