name: Check Markdown Links
run-name: ${{ github.ref_name }} by @${{ github.actor }} {{github.event.title}}
on: [push]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'no'
          config-file: 'mlc_config.json'
          folder-path: '.'
          max-depth: -1
